import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import React from "react";
import {ToastContainer} from 'react-toastify';
import "antd/dist/reset.css";
import "./globals.css";
import "../src/styles/customModal.css"
import "../src/styles/customLoading.css"
import '../src/styles/customTableTicker.css'
import {ReduxProvider} from "@/src/layout/ReduxProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Hello World",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ReduxProvider>
            {children}
        </ReduxProvider>


        <ToastContainer
            position="top-right"
            autoClose={1000}
        />
        </body>
        </html>
    );
}
